name: Build Docker Image
on: [push]

jobs:
  build:
    strategy:
      matrix:
        scheme: [small, full]
    name: Build Pari/GP [${{ matrix.scheme }}]
    runs-on: ubuntu-latest
    env:
      SCHEME: ${{ matrix.scheme }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build
        run: |
           docker build -t parigp-$SCHEME --build-arg scheme=$SCHEME .
      - name: Simple Test
        run: |
           docker run --rm parigp-$SCHEME gp --version
      - name: Deploy to Docker
        if: github.ref == 'refs/heads/master'
        run: |
           DOCKER_TAG="pascalmolin/parigp-$SCHEME"
           #docker tag parigp-$SCHEME ${DOCKER_TAG}:$VERSION
           docker tag parigp-$SCHEME ${DOCKER_TAG}:latest
           docker images $DOCKER_TAG
           echo "$DOCKER_HUB_TOKEN" | docker login --password-stdin --username pascalmolin
           docker push $DOCKER_TAG
        env:
           DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Deploy to Github
        if: github.ref == 'refs/heads/master'
        run: |
           GH_TAG="docker.pkg.github.com/mastermic/pari-docker/parigp-$SCHEME"
           docker tag parigp-$SCHEME ${GH_TAG}:latest
           docker images # $DOCKER_TAG
           echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com --password-stdin --username pascalmolin
           docker push $GH_TAG
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
